### ISSUE TITLE
rcon已经打开但是依旧不能发送指令

### ISSUE THREAD

**Issue by tingfeng3616** [KirosHan/Palworld-server-protector-DotNet#1]
rcon打开了 端口也一致 密码填的是管理员密码 但是依旧没办法用获取版本号 广播之类的指令 手动存档也是失败 是rcon密码有问题吗

**Comment by KirosHan** [comment]
可以下载v2.0.3试试，我调整了发送指令时端口和密码的捕获逻辑
另外工具需要和服务端程序运行在同一主机上，即rconHost需要是127.0.0.1

**Comment by Owen1B** [comment]
> rcon打开了 端口也一致 密码填的是管理员密码 但是依旧没办法用获取版本号 广播之类的指令 手动存档也是失败 是rcon密码有问题吗

如果你是从四人服转云的，你可以尝试一下删除服务器端存档里的WorldOption.sav文件，这个跟配置文件冲突了，可能会导致你修改配置文件不生效的情况发生

**Comment by tingfeng3616** [comment]
> 可以下载v2.0.3试试，我调整了发送指令时端口和密码的捕获逻辑 另外工具需要和服务端程序运行在同一主机上，即rconHost需要是127.0.0.1

最新版本已经修复了上面说的这些问题 但是服务端存档还是无法使用 点击后控制台提示Complete Save，但是目标文件夹下没有文件出现

**Comment by maiputgim** [comment]
![RCON](https://github.com/KirosHan/Palworld-server-protector-DotNet/assets/157928138/cad9b330-14f8-4fb7-aeca-173b228a6aef)

請問我PORT 設8211  也在伺服器安裝 為何還是無法連? 拜託解惑感恩!

**Comment by tingfeng3616** [comment]
> ![RCON](https://private-user-images.githubusercontent.com/157928138/300234233-cad9b330-14f8-4fb7-aeca-173b228a6aef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTU1NjIsIm5iZiI6MTcwNjQxNTI2MiwicGF0aCI6Ii8xNTc5MjgxMzgvMzAwMjM0MjMzLWNhZDliMzMwLTE0ZjgtNGZiNy1hZWNhLTE3M2IyMjhhNmFlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQwNDE0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmU4MTc2NTM5MmJkZjdlYTYxOWU0YjgxYTEzNDUwMjIyM2YyNDc5MmE4NzE2MTQ1NzE4MDkzNzI4YjZiMjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uVi_xrhGk8P7fMTBejjORWiOCtW-YgDNUVn0jZcs6dU)
> 
> 請問我PORT 設8211 也在伺服器安裝 為何還是無法連? 拜託解惑感恩!

需要在PalWorldSettings.ini的设置中打开Econ端口 默认应该是25575吧 然后再重新启动试试

**Comment by KirosHan** [comment]
> ![RCON](https://private-user-images.githubusercontent.com/157928138/300234233-cad9b330-14f8-4fb7-aeca-173b228a6aef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjA3OTAsIm5iZiI6MTcwNjQyMDQ5MCwicGF0aCI6Ii8xNTc5MjgxMzgvMzAwMjM0MjMzLWNhZDliMzMwLTE0ZjgtNGZiNy1hZWNhLTE3M2IyMjhhNmFlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQwNTQxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTAxZTI2ZThlZDcyYjEyNjYxYzc3OTljNTQxZWZlM2I1MzQzMmI0ZDdkMWViNDczNTEzNTU3MzM5ODk0M2FlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yAzG30re-w3-bqXJfFBewGNpClQdLgPKkVyBEKhH_uc)
> 
> 請問我PORT 設8211 也在伺服器安裝 為何還是無法連? 拜託解惑感恩!

不是8211端口，
8211端口是玩家接入的暴露端口，
请在配置文件中查看Rcon端口

**Comment by KirosHan** [comment]
> > 可以下载v2.0.3试试，我调整了发送指令时端口和密码的捕获逻辑 另外工具需要和服务端程序运行在同一主机上，即rconHost需要是127.0.0.1
> 
> 最新版本已经修复了上面说的这些问题 但是服务端存档还是无法使用 点击后控制台提示Complete Save，但是目标文件夹下没有文件出现

1.请确定服务端存档文件夹确实存在
2.请确定目标文件夹有足够的权限可以写入文件

**Comment by tingfeng3616** [comment]
服务端存档文件夹确定存在
目标文件夹为完全控制权限 可以正常写入 
但是依旧无法正常保存

**Comment by KirosHan** [comment]
> 服务端存档文件夹确定存在 目标文件夹为完全控制权限 可以正常写入 但是依旧无法正常保存

建议下载v2.2.0+版本根据配置文件和错误日志检查
