### ISSUE TITLE
希望能改一下框架，linux的mono最高支持.NET4.7.2

### ISSUE THREAD

**Issue by 247321453** [KirosHan/Palworld-server-protector-DotNet#17]
我改了一个版本
https://gitee.com/qq247321453/Palworld-server-protector-DotNet
linux安装mono后，可以运行和使用
mono Palworld-server-protector-DotNet.exe
![Uploading preview.png…]()

**Comment by KirosHan** [comment]
.net6是win7可以使用的最低版本，
采用该版本是为了向下兼容更多win系统
