### ISSUE TITLE
GUI CPU占用高和选择游戏目录卡顿

### ISSUE THREAD

**Issue by cdcp998** [KirosHan/Palworld-server-protector-DotNet#3]
GUI CPU占用高，内存占用也挺高的。。2697v3  15%的cpu 使用率 1G的内存。 和选择游戏目录卡顿

**Comment by KirosHan** [comment]
> GUI CPU占用高，内存占用也挺高的。。2697v3 15%的cpu 使用率 1G的内存。 和选择游戏目录卡顿

根据反馈来看，配置正确的情况下cpu和内存占用都趋近于0，几乎不抢占资源
可以尝试下载新版，查看错误日志信息
