### ISSUE TITLE
自定义存档目录

### ISSUE THREAD

**Issue by Chillyaaa** [KirosHan/Palworld-server-protector-DotNet#5]
当启动路径选择的非\common\PalServer下的PalServer.exe时，自动备份存档会显示找不到路径，存档的备份路径是根据根目录+下层目录这个逻辑来备份的，如果选择的是其他路径，就会出现找不到存档目录的情况，所以希望能够添加一个自定义设置存档路径的功能

**Comment by KirosHan** [comment]
已更新。
