### ISSUE TITLE
Rcon命令发送失败问题

### ISSUE THREAD

**Issue by zhuifengbaby** [KirosHan/Palworld-server-protector-DotNet#8]
![NPRMRM}J{%6 }3O91L$ 32D](https://github.com/KirosHan/Palworld-server-protector-DotNet/assets/49516539/e6881149-4042-47aa-a48b-8e584282fe30)
![image](https://github.com/KirosHan/Palworld-server-protector-DotNet/assets/49516539/641ca1c1-f4e4-4597-ab92-66384485de32)
这个Rcon端口是配置默认的25575，发送指令失败是我的管理员密码不对吗，这个密码是具体指哪个密码

**Comment by KirosHan** [comment]
密码是管理员密码，v2.2.0+版本增加了错误日志输出，可以下新版本运行再检查错误日志，本工具除了存档和自动启动，其余所有功能都依赖于Rcon所以需要确保Rcon可以正常响应。
